# Numpy

## 라이브러리 설치


In [1]:
!pip install numpy

- 설치 후 경로 확인하는 것 중요

In [94]:
import numpy as np
print (np.__version__)

2.1.1


In [4]:
# np 와 관련한 사용설명서 
# help(np)

In [28]:
num1 = [1,2,3]
num2 = [4,5,6]

IndentationError: unexpected indent (3206092298.py, line 2)

In [7]:
num1_arr = np.array(num1)
num2_arr = np.array(num2)

num1_arr + num2_arr

array([5, 7, 9])

In [30]:
num1_arr.dtype
# 속성, 메소드

dtype('int64')

In [12]:
num1_arr.shape

(3,)

In [11]:
# 차원에 대한 설명
num1_arr.ndim

1

In [29]:
num1_arr.max(axis=0)

np.int64(3)

In [32]:
num1_arr = np.array(num1,dtype='int8')
num1_arr.dtype

dtype('int8')

## 배열 만드는 방법

In [34]:
# 기본적으로 다른 데이터 자료형을 numpy 배열로 변환
# 배열 생성
print(np.ones(3))

[1. 1. 1.]


In [37]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [45]:
arr = np.ndarray(shape=(2,2),dtype=float, order='F')
arr.shape

(2, 2)

## 배열의 차원을 변경

In [48]:
temp_arr = np.arange(16)
temp_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [54]:
temp_arr.reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [56]:
# bit 맞추는 것  중요! 
# 특히 연산을 하는 경우에는 다 맞는지 확인해야함
a16 = np.array([1.333333],dtype = np.float16)
a32 = np.array([1.333333],dtype = np.float32)

print(a16)
print(a32)

[1.333]
[1.333333]


In [57]:
arr = np.array([-1,2,-3])
arr/0

/var/folders/b9/_gjz7nvj7pb9z2jrhj9r9ptr0000gn/T/ipykernel_19922/3505445433.py:2: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([-inf,  inf, -inf])

## 결측치 (missing value)
- NaN : not a number
    - 아직 정의되지 않은 숫자 의미
- Null:

In [58]:
print(type(np.nan))

<class 'float'>


In [60]:
print(np.inf, type(np.inf))

inf <class 'float'>


In [61]:
print(-np.inf, type(-np.inf))

-inf <class 'float'>


In [62]:
# 계산시 nan, inf 로 됨 
arr = np.array([-1,2,-3])
print(arr + np.nan)
print(arr + np.inf)

[nan nan nan]
[inf inf inf]


## 인덱싱 & 슬라이싱

In [65]:
arr = np.arange(10)
arr[1:5]

array([1, 2, 3, 4])

In [70]:
arr=np.arange(10).reshape(2,5)
arr[0][0]

np.int64(0)

In [74]:
arr=np.arange(10000).reshape(100,100)
# arr[0:4][0:1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [75]:
arr = np.arange(4)
arr[:2] 

array([0, 1])

In [85]:
arr = np.arange(20).reshape(4,5)
arr[1:4,2:5]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [92]:
arr = np.arange(20).reshape(2,2,5)
print(arr)
arr[1:,1:,1:] # [차원, 행, 열]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


array([[[16, 17, 18, 19]]])

## 브로드캐스팅 연산
- 배열의 크기가 다르더라도 브로드캐스팅 법칙에 의해 연산을 해주는 것

In [93]:
a = np.array([1,2,3]) 
b = 3.0
# 각각에 3.0이 들어가서 연산을 한 것 
a+b


array([4., 5., 6.])

##문제


In [100]:
#1
# arr = np.zeros(25).reshape(5,5)
np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [106]:
#2
arr = np.ndarray(shape=(3,3))
arr.dtype

dtype('float64')

In [107]:
arr.ndim

2

In [108]:
#3
arr = np.arange(16).reshape(4,4)
arr[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

## 조건 연산
- 원하는 결과값: True / False

In [109]:
arr = np.array([10,20,30])
arr > 10

array([False,  True,  True])

In [112]:
# filter
arr = np.array([18,20,30,50,16])
cond = arr > 18

arr[cond]

array([20, 30, 50])

In [113]:
arr = np.array([18,20,30,50,16])
arr[arr > 18]

array([20, 30, 50])

In [117]:
# 다중조건
arr = np.array([18,20,30,50,16,65,70])
con0 = arr > 18
con1 = arr < 65

arr[con0 & con1]  # AND

array([20, 30, 50])

In [118]:
arr[con0 | con1]  # OR

array([18, 20, 30, 50, 16, 65, 70])

In [ ]:
# 권장 사항 
# 이유: pandas 다중조건 필터링할때는 이 방법으로만 가능
arr[(con0 | con1)]

## np.where

In [121]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
# condition , x, y 
np.where (a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

## 함수와 메소드

In [129]:
arr = np.arange(8).reshape(4,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [130]:
arr.sum() # axis = None

np.int64(28)

In [131]:
arr.sum(axis=0) # x축 방향  / 행

array([12, 16])

In [132]:
arr.sum(axis=1) # y축 방향  / 열

array([ 1,  5,  9, 13])

## 무작위 랜덤 함수 

In [134]:
np.random.seed(7)     # 고정
np.random.randint(10)

4

In [135]:
np.random.randint(46, size=6) #0-45번까지의 숫자 중 무작위로 6개

array([25,  3, 19, 23, 39, 28])

In [136]:
np.random.randint(46, size=(3,3))

array([[14, 23,  8],
       [25, 42, 26],
       [ 8, 39, 38]])

In [138]:
# 0-100 까지 11개 분할
x = np.linspace(0,100,11)
print(x)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


# Pandas.Series

In [140]:
import pandas as pd
pd.__version__

'2.2.3'

In [141]:
data = [10,20,30]
s = pd.Series(data)

In [142]:
s

0    10
1    20
2    30
dtype: int64

In [143]:
print(type(s))

<class 'pandas.core.series.Series'>


In [145]:
import numpy as np

data = np.arange(5)
s = pd.Series(data)
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [147]:
data = np.arange(5)
df = pd.DataFrame(data)
df

0
0  0
1  1
2  2
3  3
4  4

In [149]:
data = ["시가","고가"]
s = pd.Series(data)
s

0    시가
1    고가
dtype: object

In [150]:
data = [80000,'90000']
s = pd.Series(data)
s

0    80000
1    90000
dtype: object

## 시리즈 인덱스

In [155]:
data = [1000,2000,3000]
s = pd.Series(data)
print(s.index, type(s.index))

RangeIndex(start=0, stop=3, step=1) <class 'pandas.core.indexes.range.RangeIndex'>


In [156]:
list(s.index)

[0, 1, 2]

In [157]:
s.index.to_list()

[0, 1, 2]

In [170]:
# 시리즈 생성하면서 인덱스도 같이 생성
data = [1000,2000,3000]
index = ['메로나','월드콘','와']

s = pd.Series(data, index)
s

메로나    1000
월드콘    2000
와      3000
dtype: int64

In [162]:
s.index

Index(['메로나', '월드콘', '와'], dtype='object')

In [164]:
s.values, type(s.values)
# 타입이 numpy이기 때문에 이 형태에서는 numpy에서 사용하는 연산들 가능함

(array([[1000],
        [2000],
        [3000]]),
 numpy.ndarray)

## 시리즈 인덱싱
- iloc ( 값을 통해서 접근 / 위치 기반 )
  - ETL 경우 사용 ( 속도가 더 빠름 )
  - 슬라이싱 기반으로 접근
- loc ( 이름 기반 / label 기반 )
- DataFrame 사용시 loc 를 기본값으로 생각하면 됨
  - 아무래도 feature에 이름이 있기 때문이 아닐까..?

In [181]:
s.iloc[:3]

메로나    1000
월드콘    2000
와      3000
dtype: int64

In [180]:
s.loc["메로나":"와"]

메로나    1000
월드콘    2000
와      3000
dtype: int64

In [165]:
print(s.iloc[0])

0    1000
Name: 메로나, dtype: int64


In [167]:
print(s.loc['메로나']) # dict 같은 너낌~

0    1000
Name: 메로나, dtype: int64


In [175]:
data = [1000,2000,3000]
# index가 없음

s2 = pd.Series(data)
s2.index.to_list()
# print(s2.iloc[0])
# print(s2.loc['메로나'])

[0, 1, 2]

In [ ]:
print(s2.iloc[0])  # iloc 에서의 0은 위치 0을 의미
print(s2.loc[0])   # loc 에서의 0은 라벨 0을 의미 


## 슬라이싱
- iloc[0:3] -> 0-2 출력
- loc[0:3] -> 0-3 출력